package almoxarifado;

import javax.swing.JDialog;
import javax.swing.JFormattedTextField;

import javax.swing.JOptionPane;

class JDialogSolicitar extends JDialog {
//Classe que gerencia a TELA para efetuação de uma Solicitação.

    Solicitacao solicitacao = new Solicitacao();

    protected JDialogSolicitar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();

    }

    private void init() {   //Init manualmente personalizado para melhor controle.

        setTitle("Solicitação");
        setVisible(true);
        setLocationRelativeTo(null);

        if (JListaConsultarEstoque.getValueIsAdjusting() == true) {
            if (jListaProdutosSolicitacao.getSelectedIndex() == -1) {
                //Sem seleção, desativa o botão.
                jButtonSelecionarProduto.setEnabled(false);

            } else {
                //Seleção, ativa o botão.
                jButtonSelecionarProduto.setEnabled(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonCancelaProduto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListaProdutosSolicitacao = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        JListaConsultarEstoque = new javax.swing.JList<>();
        jButtonSelecionarProduto = new javax.swing.JButton();
        jLabelEstoque = new javax.swing.JLabel();
        jLabelSolicitacao = new javax.swing.JLabel();
        jComboSiglaDepartamento = new javax.swing.JComboBox<>();
        jButtonFinalizarSolicitacao = new javax.swing.JButton();
        jTextFieldDataPedido = new javax.swing.JFormattedTextField();
        jLabelDataPedido = new javax.swing.JLabel();
        jLabelSiglaDepartamento = new javax.swing.JLabel();
        jLabelTotalProdutos = new javax.swing.JLabel();
        jTextFieldTotalProdutos = new javax.swing.JTextField();
        jLabelValorTotal = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jButtonCancelarSolicitacao = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jButtonCancelaProduto.setText("Cancelar Produto");
        jButtonCancelaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelaProdutoActionPerformed(evt);
            }
        });

        jListaProdutosSolicitacao.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = solicitacao.produtoArray();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListaProdutosSolicitacao.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jListaProdutosSolicitacao);

        JListaConsultarEstoque.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = almoxarifado.GerenciadorEstoque.estoqueArray();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JListaConsultarEstoque.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(JListaConsultarEstoque);

        jButtonSelecionarProduto.setText("Selecionar Produto");
        jButtonSelecionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarProdutoActionPerformed(evt);
            }
        });

        jLabelEstoque.setText("Estoque");

        jLabelSolicitacao.setText("Solicitação");

        jComboSiglaDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(GerenciadorDepartamentos.GerenciadorDepartamentosSiglaArray()));

        jButtonFinalizarSolicitacao.setText("Finalizar Solicitação");
        jButtonFinalizarSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarSolicitacaoActionPerformed(evt);
            }
        });

        almoxarifado.UtilMascaras.maskOnlyDate(jTextFieldDataPedido);

        jLabelDataPedido.setText("Data Pedido:");

        jLabelSiglaDepartamento.setText("Dep/Setor:");

        jLabelTotalProdutos.setText("Total:");

        jTextFieldTotalProdutos.setEditable(false);

        jLabelValorTotal.setText("Valor Total: ");

        jTextFieldValorTotal.setEditable(false);

        jButtonCancelarSolicitacao.setText("Cancelar Solicitação");
        jButtonCancelarSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarSolicitacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelDataPedido)
                                            .addGap(100, 100, 100))
                                        .addComponent(jTextFieldDataPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(149, 149, 149)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboSiglaDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelSiglaDepartamento))
                                    .addGap(22, 22, 22))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTotalProdutos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldTotalProdutos)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonCancelaProduto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelValorTotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButtonFinalizarSolicitacao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabelSolicitacao)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCancelarSolicitacao)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelEstoque)
                                .addGap(203, 203, 203))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonSelecionarProduto)
                                .addGap(163, 163, 163))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstoque)
                    .addComponent(jLabelSolicitacao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDataPedido)
                            .addComponent(jLabelSiglaDepartamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboSiglaDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(jButtonFinalizarSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSelecionarProduto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonCancelaProduto)
                                .addComponent(jLabelValorTotal)
                                .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelTotalProdutos)
                                .addComponent(jTextFieldTotalProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelaProdutoActionPerformed

        if (jListaProdutosSolicitacao.getSelectedIndex() != -1) {

            solicitacao.cancelaProduto(solicitacao.getProdutos().get(jListaProdutosSolicitacao.getSelectedIndex()));
            refazListaSolicitacao();
            refazListaEstoque();
        } else {
        }
    }//GEN-LAST:event_jButtonCancelaProdutoActionPerformed

    private void jButtonSelecionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarProdutoActionPerformed

        if (JListaConsultarEstoque.getSelectedIndex() != -1) {

            JFormattedTextField quantidadeProduto = new JFormattedTextField();  //Novo jFormattedTextField para aplicação das máscaras.

            UtilMascaras.maskOnlyInt(quantidadeProduto);    //Aplica máscara para permitir apenas números inteiros

            JOptionPane.showMessageDialog(null, quantidadeProduto, "Insira a quantidade do Produto.", JOptionPane.PLAIN_MESSAGE);

            String quantidadeProdutoString = quantidadeProduto.getText().replace(" ", "");  //Apaga possíveis espaços que atrapalhariam na conversão.
            int quantidade = 0;

            verificaSeQuantidadeVazia(quantidadeProdutoString, quantidade);   //Verifica se a quantidade não é vazia para continuar.
        
        }
    }//GEN-LAST:event_jButtonSelecionarProdutoActionPerformed

    private void jButtonFinalizarSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarSolicitacaoActionPerformed

        if (solicitacao.getProdutos().size() > 0 && jComboSiglaDepartamento.getSelectedIndex() != -1 && jTextFieldDataPedido.getText() != null) {
            
            solicitacao.setDestino(GerenciadorDepartamentos.listaDepartamentos.get(jComboSiglaDepartamento.getSelectedIndex()));
            
            if(solicitacao.setDataPedido(jTextFieldDataPedido.getText()) == true){
            
                GerenciadorSolicitacoes.adicionaSolicitacao(solicitacao);
                solicitacao.finalizaSolicitacao();
                JOptionPane.showMessageDialog(null, "Solicitação efetuada com Sucesso!\nCod: "+solicitacao.getSolicitacaoID());
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Informe uma data válida!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Informe todos os campos da Solicitação!");
        }
    }//GEN-LAST:event_jButtonFinalizarSolicitacaoActionPerformed

    private void jButtonCancelarSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarSolicitacaoActionPerformed
        solicitacao.getProdutos().forEach((produto) -> {
            int reposicao = solicitacao.getProdutos().get(solicitacao.getProdutos().indexOf(produto)).getQuantidadeSolicitacao()
                    + GerenciadorEstoque.estoque.get(GerenciadorEstoque.estoque.indexOf(produto)).getQuantidade();

            GerenciadorEstoque.repoeProduto(produto, reposicao);
        });

        dispose();
    }//GEN-LAST:event_jButtonCancelarSolicitacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    private static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogSolicitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogSolicitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogSolicitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogSolicitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JDialogSolicitar dialog = new JDialogSolicitar(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    private void atualizaJTextFieldTotais() {   //Atualiza as caixas de texto dos totais.
        jTextFieldTotalProdutos.setText(String.valueOf(solicitacao.getNumeroPedidos()));
        jTextFieldValorTotal.setText(String.valueOf(solicitacao.getValorTotal()));
    }

    private void refazListaSolicitacao() {  //Refaz a lista da tela para atualização dos dados

        atualizaJTextFieldTotais();

        jListaProdutosSolicitacao.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = solicitacao.produtoArray();

            @Override
            public int getSize() {
                return strings.length;
            }

            @Override
            public String getElementAt(int i) {
                return strings[i];
            }
        });

        jScrollPane2.setViewportView(jListaProdutosSolicitacao);

    }

    private void refazListaEstoque() {

        JListaConsultarEstoque.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = GerenciadorEstoque.estoqueArray();

            @Override
            public int getSize() {
                return strings.length;
            }

            @Override
            public String getElementAt(int i) {
                return strings[i];
            }
        });

        jScrollPane3.setViewportView(JListaConsultarEstoque);

    }
    
        private void verificaSeQuantidadeVazia(String quantidadeProdutoString, int quantidade) {
            if (quantidadeProdutoString.equals("")) { 

            } else {
                quantidade = Integer.parseInt(quantidadeProdutoString);
                if (quantidade > 0) {
                    solicitacao.adicionaProduto(JListaConsultarEstoque.getSelectedIndex(), quantidade);
                    refazListaSolicitacao();
                    refazListaEstoque();
                } else {
                    JOptionPane.showMessageDialog(null, "Insira ao menos 1 produto à sua Solicitação");
                }

            }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JListaConsultarEstoque;
    private javax.swing.JButton jButtonCancelaProduto;
    private javax.swing.JButton jButtonCancelarSolicitacao;
    private javax.swing.JButton jButtonFinalizarSolicitacao;
    private javax.swing.JButton jButtonSelecionarProduto;
    private javax.swing.JComboBox<String> jComboSiglaDepartamento;
    private javax.swing.JLabel jLabelDataPedido;
    private javax.swing.JLabel jLabelEstoque;
    private javax.swing.JLabel jLabelSiglaDepartamento;
    private javax.swing.JLabel jLabelSolicitacao;
    private javax.swing.JLabel jLabelTotalProdutos;
    private javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListaProdutosSolicitacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JFormattedTextField jTextFieldDataPedido;
    private javax.swing.JTextField jTextFieldTotalProdutos;
    private javax.swing.JTextField jTextFieldValorTotal;
    // End of variables declaration//GEN-END:variables


}
