package almoxarifado;

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

class JDialogDepartamentos extends javax.swing.JDialog {
//Esta classe Swing é responsável pela TELA de Gerenciamento de Departamentos.


    protected JDialogDepartamentos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    private void init() {   //Init manualmente personalizado para melhor controle.
        setTitle("Departamentos e Setores");
        setVisible(true);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTTN_addDepartamento = new javax.swing.JButton();
        BTTN_removeDepartamento = new javax.swing.JButton();
        jPanelPrintEstoque = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDepartamentos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(getLocation());
        setResizable(false);

        BTTN_addDepartamento.setText("Adicionar");
        BTTN_addDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTTN_addDepartamentoActionPerformed(evt);
            }
        });

        BTTN_removeDepartamento.setText("Remover");
        BTTN_removeDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTTN_removeDepartamentoActionPerformed(evt);
            }
        });

        jPanelPrintEstoque.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        jListDepartamentos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = GerenciadorDepartamentos.GerenciadorDepartamentosArray();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListDepartamentos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListDepartamentos.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jListDepartamentos.setDoubleBuffered(true);
        jListDepartamentos.setDragEnabled(true);
        jScrollPane1.setViewportView(jListDepartamentos);

        javax.swing.GroupLayout jPanelPrintEstoqueLayout = new javax.swing.GroupLayout(jPanelPrintEstoque);
        jPanelPrintEstoque.setLayout(jPanelPrintEstoqueLayout);
        jPanelPrintEstoqueLayout.setHorizontalGroup(
            jPanelPrintEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrintEstoqueLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelPrintEstoqueLayout.setVerticalGroup(
            jPanelPrintEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelPrintEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTTN_addDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTTN_removeDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrintEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTTN_addDepartamento)
                    .addComponent(BTTN_removeDepartamento))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(null);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTTN_addDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTTN_addDepartamentoActionPerformed

        JFormattedTextField nomeDepartamento = new JFormattedTextField();
        JFormattedTextField siglaDepartamento = new JFormattedTextField();

        UtilMascaras.maskOnlyString(nomeDepartamento);
        UtilMascaras.maskOnlyString3chars(siglaDepartamento);

        Object[] campos = {
            "Nome do Departamento/Setor", nomeDepartamento,
            "Sigla", siglaDepartamento,};

        JOptionPane.showMessageDialog(null, campos, "Adicionar Departamento ou Setor", JOptionPane.QUESTION_MESSAGE);
        
        String nomeDepartamentoString = nomeDepartamento.getText().replace(" ", "");
        String siglaDepartamentoString = siglaDepartamento.getText().replace(" ", "");

        if (!nomeDepartamentoString.isEmpty() && !siglaDepartamentoString.isEmpty()) {
            Departamento novoDepartamento = new Departamento(nomeDepartamentoString, siglaDepartamentoString);

        }else{
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.");
        }
        refazLista();

    }//GEN-LAST:event_BTTN_addDepartamentoActionPerformed

    private void BTTN_removeDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTTN_removeDepartamentoActionPerformed
        if(jListDepartamentos.getSelectedIndex() > -1){
            GerenciadorDepartamentos.removeDepartamento(jListDepartamentos.getSelectedIndex());
        }
        refazLista();
    }//GEN-LAST:event_BTTN_removeDepartamentoActionPerformed

    /**
     * @param args the command line argumentst
     */
    private static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogDepartamentos dialog = new JDialogDepartamentos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void refazLista() { //Refaz a lista visual para atualiza-lá na tela.

        jListDepartamentos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = GerenciadorDepartamentos.GerenciadorDepartamentosArray();

            @Override
            public int getSize() {
                return strings.length;
            }

            @Override
            public String getElementAt(int i) {
                return strings[i];
            }
        });

        jScrollPane1.setViewportView(jListDepartamentos);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTTN_addDepartamento;
    private javax.swing.JButton BTTN_removeDepartamento;
    private javax.swing.JList<String> jListDepartamentos;
    private javax.swing.JPanel jPanelPrintEstoque;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
